{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SotoCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"role":"symbol","title":"context","externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","roleHeading":"Instance Property","symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"variants":[{"paths":["\/documentation\/sotocore\/awsservererror\/context"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"additional context information related to the error"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["Linux"]}],"kind":"declarations"}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"url":"\/documentation\/sotocore\/awsservererror\/context","kind":"symbol","title":"context","role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","abstract":[{"text":"additional context information related to the error","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"title":"AWSServerError","url":"\/documentation\/sotocore\/awsservererror","type":"topic","abstract":[],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSServerError"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"title":"AWSErrorContext","url":"\/documentation\/sotocore\/awserrorcontext","type":"topic","abstract":[{"text":"Additional information about error","type":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSErrorContext"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}]},"doc://codes.soto.soto-core/documentation/SotoCore":{"role":"collection","url":"\/documentation\/sotocore","kind":"symbol","title":"SotoCore","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore"}}}