{"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"SotoCore"}],"externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","symbolKind":"property","title":"context","role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"text":"additional context information related to the error","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"variants":[{"paths":["\/documentation\/sotocore\/awsservererror\/context"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"typeIdentifier","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"platforms":["Linux"],"languages":["swift"]}]}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","title":"AWSErrorContext","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSErrorContext"}],"navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"url":"\/documentation\/sotocore\/awserrorcontext","abstract":[{"text":"Additional information about error","type":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sotocore\/awsservererror\/context","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","title":"context","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"additional context information related to the error"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}],"kind":"symbol","title":"AWSServerError","navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/sotocore\/awsservererror","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","kind":"symbol","role":"collection","url":"\/documentation\/sotocore","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore"}}}