{"variants":[{"paths":["\/documentation\/sotocore\/awsservererror\/context"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"title":"context","roleHeading":"Instance Property","role":"symbol","externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","modules":[{"name":"SotoCore"}]},"abstract":[{"text":"additional context information related to the error","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["Linux"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"navigatorTitle":[{"text":"AWSErrorContext","kind":"identifier"}],"url":"\/documentation\/sotocore\/awserrorcontext","type":"topic","kind":"symbol","title":"AWSErrorContext","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}],"abstract":[{"text":"Additional information about error","type":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext"},"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","title":"SotoCore","role":"collection","type":"topic","url":"\/documentation\/sotocore","kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"title":"context","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"additional context information related to the error"}],"url":"\/documentation\/sotocore\/awsservererror\/context"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}],"url":"\/documentation\/sotocore\/awsservererror","kind":"symbol","title":"AWSServerError","abstract":[],"type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSServerError"}]}}}