{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/internalfailure"]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"kind":"symbol","metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalFailure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSServerError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"}],"roleHeading":"Type Property","modules":[{"name":"SotoCore"}],"role":"symbol","symbolKind":"property","title":"internalFailure","externalID":"s:8SotoCore14AWSServerErrorV15internalFailureACvpZ"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Linux"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"title":"AWSServerError","navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"url":"\/documentation\/sotocore\/awsservererror","type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/internalFailure":{"kind":"symbol","title":"internalFailure","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/sotocore\/awsservererror\/internalfailure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError"}]},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","url":"\/documentation\/sotocore","kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","role":"collection","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}]}}}