{"abstract":[{"text":"additional context information related to the error","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsresponseerror\/context"]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError"]]},"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"externalID":"s:8SotoCore16AWSResponseErrorV7contextAA15AWSErrorContextVSgvp","title":"context","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"SotoCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["Linux"]}]}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","url":"\/documentation\/sotocore","kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","role":"collection","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError/context":{"type":"topic","url":"\/documentation\/sotocore\/awsresponseerror\/context","title":"context","role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context","kind":"symbol","abstract":[{"text":"additional context information related to the error","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"kind":"symbol","title":"AWSErrorContext","navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","role":"symbol","type":"topic","abstract":[{"text":"Additional information about error","type":"text"}],"url":"\/documentation\/sotocore\/awserrorcontext","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSErrorContext"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSResponseError"}],"title":"AWSResponseError","url":"\/documentation\/sotocore\/awsresponseerror","kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError","role":"symbol","abstract":[{"text":"Response Error type returned by Soto if the error code is unrecognised","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AWSResponseError"}]}}}