{"abstract":[{"type":"text","text":"additional context information related to the error"}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:8SotoCore16AWSResponseErrorV7contextAA15AWSErrorContextVSgvp","modules":[{"name":"SotoCore"}],"title":"context"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"platforms":["Linux"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsresponseerror\/context"]}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"url":"\/documentation\/sotocore","title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","type":"topic","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"role":"collection","kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError/context":{"title":"context","abstract":[{"text":"additional context information related to the error","type":"text"}],"role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/sotocore\/awsresponseerror\/context"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"title":"AWSErrorContext","url":"\/documentation\/sotocore\/awserrorcontext","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSErrorContext"}],"navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"abstract":[{"text":"Additional information about error","type":"text"}],"role":"symbol","kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError","url":"\/documentation\/sotocore\/awsresponseerror","title":"AWSResponseError","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSResponseError","kind":"identifier"}],"navigatorTitle":[{"text":"AWSResponseError","kind":"identifier"}],"abstract":[{"type":"text","text":"Response Error type returned by Soto if the error code is unrecognised"}],"role":"symbol","kind":"symbol"}}}