{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/sotocore\/awsresponseerror\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/message","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AWSErrorType.message"},{"type":"text","text":"."}],"metadata":{"modules":[{"name":"SotoCore"}],"title":"message","externalID":"s:8SotoCore12AWSErrorTypePAAE7messageSSSgvp::SYNTHESIZED::s:8SotoCore16AWSResponseErrorV","extendedModule":"SotoCore","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError"]]},"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","role":"collection","kind":"symbol","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError":{"role":"symbol","title":"AWSResponseError","abstract":[{"type":"text","text":"Response Error type returned by Soto if the error code is unrecognised"}],"type":"topic","url":"\/documentation\/sotocore\/awsresponseerror","navigatorTitle":[{"text":"AWSResponseError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"AWSResponseError","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError/message":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/sotocore\/awsresponseerror\/message","kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/message","role":"symbol","abstract":[],"title":"message"}}}