{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRetryWaitTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"attempt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:8SotoCore11RetryStatusO","text":"RetryStatus","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:8SotoCore11RetryPolicyP03getC8WaitTime5error7attemptAA0C6StatusOSgs5Error_p_SitF","symbolKind":"method","modules":[{"name":"SotoCore"}],"title":"getRetryWaitTime(error:attempt:)","role":"symbol","roleHeading":"Instance Method","required":true},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRetryWaitTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attempt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryStatus","preciseIdentifier":"s:8SotoCore11RetryStatusO","kind":"typeIdentifier","text":"RetryStatus"},{"kind":"text","text":"?"}],"platforms":["Linux"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error returned by HTTP client"}]}]},{"name":"attempt","content":[{"inlineContent":[{"text":"Retry attempt number","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy\/getRetryWaitTime(error:attempt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns whether we should retry and how long we should wait before retrying"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/retrypolicy\/getretrywaittime(error:attempt:)"]}],"kind":"symbol","sections":[],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/RetryStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RetryStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/sotocore\/retrystatus","role":"symbol","abstract":[{"type":"text","text":"Return value for "},{"type":"codeVoice","code":"RetryPolicy.getRetryWaitTime"},{"type":"text","text":". Either retry after time amount or donâ€™t retry"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryStatus","title":"RetryStatus","navigatorTitle":[{"text":"RetryStatus","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","url":"\/documentation\/sotocore","role":"collection","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","title":"SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/RetryPolicy/getRetryWaitTime(error:attempt:)":{"abstract":[{"text":"Returns whether we should retry and how long we should wait before retrying","type":"text"}],"kind":"symbol","url":"\/documentation\/sotocore\/retrypolicy\/getretrywaittime(error:attempt:)","role":"symbol","title":"getRetryWaitTime(error:attempt:)","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy\/getRetryWaitTime(error:attempt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRetryWaitTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":", ","kind":"text"},{"text":"attempt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"RetryStatus","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore11RetryStatusO"},{"text":"?","kind":"text"}],"type":"topic","required":true},"doc://codes.soto.soto-core/documentation/SotoCore/RetryPolicy":{"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy","abstract":[{"type":"text","text":"Protocol for Retry strategy. Has function returning amount of time before the next retry after an HTTP error"}],"title":"RetryPolicy","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RetryPolicy"}],"navigatorTitle":[{"kind":"identifier","text":"RetryPolicy"}],"url":"\/documentation\/sotocore\/retrypolicy"}}}