{"abstract":[{"type":"text","text":"Returns whether we should retry and how long we should wait before retrying"}],"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"SotoCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRetryWaitTime","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attempt"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"RetryStatus","preciseIdentifier":"s:8SotoCore11RetryStatusO","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"getRetryWaitTime(error:attempt:)","required":true,"externalID":"s:8SotoCore11RetryPolicyP03getC8WaitTime5error7attemptAA0C6StatusOSgs5Error_p_SitF","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRetryWaitTime","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":", ","kind":"text"},{"text":"attempt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryStatus","text":"RetryStatus","preciseIdentifier":"s:8SotoCore11RetryStatusO"},{"text":"?","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Error returned by HTTP client","type":"text"}]}],"name":"error"},{"name":"attempt","content":[{"type":"paragraph","inlineContent":[{"text":"Retry attempt number","type":"text"}]}]}],"kind":"parameters"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/retrypolicy\/getretrywaittime(error:attempt:)"]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy\/getRetryWaitTime(error:attempt:)","interfaceLanguage":"swift"},"references":{"doc://codes.soto.soto-core/documentation/SotoCore/RetryStatus":{"navigatorTitle":[{"text":"RetryStatus","kind":"identifier"}],"title":"RetryStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RetryStatus"}],"type":"topic","abstract":[{"type":"text","text":"Return value for "},{"type":"codeVoice","code":"RetryPolicy.getRetryWaitTime"},{"text":". Either retry after time amount or donâ€™t retry","type":"text"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryStatus","url":"\/documentation\/sotocore\/retrystatus","role":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","role":"collection","kind":"symbol","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/RetryPolicy":{"url":"\/documentation\/sotocore\/retrypolicy","role":"symbol","title":"RetryPolicy","type":"topic","navigatorTitle":[{"text":"RetryPolicy","kind":"identifier"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RetryPolicy"}],"kind":"symbol","abstract":[{"text":"Protocol for Retry strategy. Has function returning amount of time before the next retry after an HTTP error","type":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/RetryPolicy/getRetryWaitTime(error:attempt:)":{"url":"\/documentation\/sotocore\/retrypolicy\/getretrywaittime(error:attempt:)","role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy\/getRetryWaitTime(error:attempt:)","title":"getRetryWaitTime(error:attempt:)","abstract":[{"type":"text","text":"Returns whether we should retry and how long we should wait before retrying"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRetryWaitTime"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"attempt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:8SotoCore11RetryStatusO","kind":"typeIdentifier","text":"RetryStatus"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic"}}}