{"variants":[{"paths":["\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Waiter failed, but without an error. ie a successful api call was an error","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"waiterFailed","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError","text":"ClientError","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"SotoCore"}],"externalID":"s:8SotoCore9AWSClientC11ClientErrorV12waiterFailedAEvpZ","roleHeading":"Type Property","title":"waiterFailed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiterFailed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","kind":"typeIdentifier","text":"ClientError"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError"]]},"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","kind":"symbol","type":"topic","role":"collection"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWSClient"}],"type":"topic","title":"AWSClient","abstract":[{"type":"text","text":"Client managing communication with AWS services"}],"navigatorTitle":[{"text":"AWSClient","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","url":"\/documentation\/sotocore\/awsclient"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError":{"abstract":[{"text":"Errors returned by ","type":"text"},{"type":"codeVoice","code":"AWSClient"},{"type":"text","text":" code"}],"role":"symbol","title":"AWSClient.ClientError","navigatorTitle":[{"kind":"identifier","text":"ClientError"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ClientError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sotocore\/awsclient\/clienterror","type":"topic"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError/waiterFailed":{"title":"waiterFailed","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiterFailed","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","kind":"typeIdentifier","text":"ClientError"}],"abstract":[{"type":"text","text":"Waiter failed, but without an error. ie a successful api call was an error"}],"url":"\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed","type":"topic"}}}